### ISSUE TITLE
WinUSBDongle constructor interface mismatch

### ISSUE THREAD

**Issue by ulrichard** [LedgerHQ/btchip-python#15]
After updating to the most recent version, my HW1 with WinUSB does no longer work. 
At first sight it might be because the interface doesn't match :

class WinUSBDongle(Dongle, DongleWait):
    def __init__(self, device, debug=False):

...

return WinUSBDongle(dev, ledger, debug)

I can get it to work by simply removing the ledger variable from the instantiation. Although I have no idea if that's the right fix.

**Comment by btchip** [comment]
You're right, I just pushed a fix for that - thanks for reporting.
