### ISSUE TITLE
Support for newer firmware releases

### ISSUE THREAD

**Issue by ulrichard** [LedgerHQ/btchip-python#19]
I have to HW1 that work with btchip-python, and two that don't. 
The test I use is samples/getFirmwareVersion.py
The ones that work have firmware version 1.4.10  and  1.4.14
The ones that don't work are:
1) upgraded to the latest firmware with the chromium plugin a few days ago.
2) received per mail today and set up with Ledger Starter.

So it appears to me, the python lib doesn't support newer firmwares.

**Comment by btchip** [comment]
Which error do you get ?

The other parts should work fine, because I'm using them in Electrum.

On 10 February 2016 at 22:58, Richard <notifications@github.com> wrote:

> I have to HW1 that work with btchip-python, and two that don't.
> The test I use is samples/getFirmwareVersion.py
> The ones that work have firmware version 1.4.10 and 1.4.14
> The ones that don't work are:
> 1) upgraded to the latest firmware with the chromium plugin a few days ago.
> 2) received per mail today and set up with Ledger Starter.
>
> So it appears to me, the python lib doesn't support newer firmwares.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LedgerHQ/btchip-python/issues/19>.
>



-- 
Nicolas Bacca
CEO <http://www.simulity.com/>
Mobile +33 6 30 79 86 54 - Skype nicolas_bacca.pro

**Comment by ulrichard** [comment]
I have them at home. Will check in the evening. 
The error was something to do with hdi.
I didn't check the transport. Could it be that they are still shipped with the old transport enabled, and I have to switch them to the new one?

**Comment by ulrichard** [comment]
I had to adjust the udev rules. 

The old ones were: 
2581:2b7c

and the new ones:
2581:3b7c

**Comment by ulrichard** [comment]
Since I will  make a new debian package with the revised udev rules, would it make sense to make a new release with the changes since v0.1.16?

**Comment by btchip** [comment]
I don't have pending changes for the time being. Probably some in a few
weeks for SegWit support.

On 11 February 2016 at 21:21, Richard <notifications@github.com> wrote:

> Since I will make a new debian package with the revised udev rules, would
> it make sense to make a new release with the changes since v0.1.16?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LedgerHQ/btchip-python/issues/19#issuecomment-183047656>
> .
>



-- 
Nicolas Bacca
CEO <http://www.simulity.com/>
Mobile +33 6 30 79 86 54 - Skype nicolas_bacca.pro

**Comment by ulrichard** [comment]
Ah, right. I thought there were some commits since the last release, but you're right.
