### ISSUE TITLE
getTrustedInput crashes with funds sent from segwit addresses

### ISSUE THREAD

**Issue by ecdsa** [LedgerHQ/btchip-python#30]
see https://github.com/spesmilo/electrum/commit/1ecfcea8dcfe37df4c6dceeaf071f19c7660c44b

**Comment by btchip** [comment]
Mmh, this code is not supposed to be called from a Segwit UTXO - also disabling it would break all non Segwit transactions

**Comment by ecdsa** [comment]
@btchip this code breaks when the funding transaction of a non-segwit utxo is a segwit transaction.

well, it is not the code that breaks, it is the ledger firmware

**Comment by ecdsa** [comment]
fixed in 7ea64d0330b0c2bbda5d60cfb91f13b5b3e7b7b6
