### ISSUE TITLE
Invalid Channel

### ISSUE THREAD

**Issue by deathbybinary** [LedgerHQ/btchip-python#37]
Having issues trying to connect my Ledger Nano S (Firmware 1.31) to Electron-Cash 3.1.2 OSX running the Bitcoin Cash Ledger app (v1.1.5).

The application correctly detects my Ledger device however attempting to establish a connection results in the error: "Exception: Invalid Channel"

I have been working with the developer of the application to isolate the issue and it appears to be a btchip-python error message:
https://github.com/LedgerHQ/btchip-python/blob/master/btchip/ledgerWrapper.py#L55
https://github.com/LedgerHQ/btchip-python/blob/master/btchip/ledgerWrapper.py#L78

Could this be a problem with the Ledger Bitcoin Cash App? If I launch the Bitcoin App instead I receive a different error - "HW1 firmware version too old. Please update at ledgerwallet.com" and the Bitcoin app works fine with electrum (https://github.com/spesmilo/electrum) whose code was forked for the BCH variant. 

Please help!

Cheers

**Comment by btchip** [comment]
Please check that Brower Support is set to Off in the app settings

**Comment by deathbybinary** [comment]
That did the trick, thank you so much!
