### ISSUE TITLE
__version__ attribute

### ISSUE THREAD

**Issue by marceloneil** [LedgerHQ/btchip-python#39]
Implement the module `__version__` attribute from [PEP 396](https://www.python.org/dev/peps/pep-0396/).

Example behavior:
```python
>>> import btchip
>>> btchip.__version__
'0.1.27'
```

This is useful for developers to better handle different versions of python-btchip, and their respective feature-sets.

**Comment by SomberNight** [comment]
Yes please; I would use it as in https://github.com/spesmilo/electrum/commit/91c369e39288328f24fedc70e36eda67f5ad6dd3

**Comment by SomberNight** [comment]
note: this was done in https://github.com/LedgerHQ/btchip-python/commit/9ec21ec6cdad25211f25298508b4ee4788b7f0fa
